manbooks/urls.py
from django.conf.urls import url

from . import views

app_name = 'manbooks'
urlpatterns = [
     url(r'^$', views.IndexView.as_view(), name='index'),
     url(r'(?P<pk>[0-9]+)/$', 
        views.DetailView.as_view(), name='detail'),
     url(r'^newbook/$', views.newbook, name='newbook'),
     url(r'^addnew/$', views.addnew, name='addnew'),
     url(r'^(?P<book_id>[0-9]+)/delbook/$', views.delbook, name='delbook'),
]

manbooks/models.py
import datetime
from django.db import models
from django.utils import timezone

class Book(models.Model):
    book_name = models.CharField(max_length=200)
    author_name = models.CharField(max_length=200)
    link_addr = models.CharField(max_length=200)
    pub_year = models.IntegerField()
    def __str__(self):
        return self.book_name

manbooks/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.template import loader
from django.shortcuts import render, redirect

from .models import Book

class IndexView(generic.ListView):
    template_name = 'manbooks/index.html'
    context_object_name = 'all_book_list'

    def get_queryset(self):
        return Book.objects.all()

class DetailView(generic.DetailView):
    model = Book
    template_name = 'manbooks/detail.html'

def newbook(request):
    # return HttpResponseRedirect(reverse('manbooks:newbook'))
    return render(request, 'manbooks/newbook.html')

def addnew(request):
    abook = Book(book_name = request.POST['bookname'],
        author_name=request.POST['authorname'],
        link_addr=request.POST['linkaddr'],
        pub_year=request.POST['pubyear'])
    abook.save()
    return HttpResponseRedirect('/manbooks')

def delbook(request, book_id):
    book=Book.objects.get(pk=book_id)
    book.delete()
    return HttpResponseRedirect('/manbooks')

manbooks/templates/manbooks/detail.html
<h1>{{ book.book_name }}</h1>
<p>Auther: {{ book.author_name }} </p>
<p>Published date: {{ book.pub_year }} </p>
<p>Link: {{ book.link_addr }} </p>
<a href="{% url 'manbooks:delbook' book.id %}">Delete</a>

manbooks/templates/manbooks/index.html
{% if all_book_list %}
<h1>Books list</h1>
<ul>
    {% for book in all_book_list %}
        <li>
            <a href="/manbooks/{{ book.id }}/">
                {{ book.book_name }}
            </a>
        </li>
    {% endfor %}
</ul>
{% else %}
    <p>No books are available</p>
{% endif %}

<a href="{% url 'manbooks:newbook' %}">Add new book</a>

manbooks/templates/manbooks/newbook.html
<h1>Add new book</h1>
<form action="{% url 'manbooks:addnew' %}" method="post">
{% csrf_token %}
    <ul>
        <li>Book name<br \>
        <input type="text" name="bookname" id="bookname">
        </li>
        <li>Author name<br \>
        <input type="text" name="authorname" id="authorname">
        </li>
        <li>Publication date<br \>
        <input type="text" name="pubyear" id="pubyear">
        </li>
        <li>Link address<br \>
        <input type="text" name="linkaddr" id="linkaddr">
        </li>
    </ul>
    <input type="submit" name="Add">
</form>